// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rlaplace_cpp
NumericVector rlaplace_cpp(int n, double scale);
RcppExport SEXP _DPrivStats_rlaplace_cpp(SEXP nSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(rlaplace_cpp(n, scale));
    return rcpp_result_gen;
END_RCPP
}
// clip_gradients_cpp
NumericMatrix clip_gradients_cpp(NumericMatrix grads, double max_grad_norm);
RcppExport SEXP _DPrivStats_clip_gradients_cpp(SEXP gradsSEXP, SEXP max_grad_normSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type grads(gradsSEXP);
    Rcpp::traits::input_parameter< double >::type max_grad_norm(max_grad_normSEXP);
    rcpp_result_gen = Rcpp::wrap(clip_gradients_cpp(grads, max_grad_norm));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DPrivStats_rlaplace_cpp", (DL_FUNC) &_DPrivStats_rlaplace_cpp, 2},
    {"_DPrivStats_clip_gradients_cpp", (DL_FUNC) &_DPrivStats_clip_gradients_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DPrivStats(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
