# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rlaplace_cpp <- function(n, scale) {
    .Call('_DPrivStats_rlaplace_cpp', PACKAGE = 'DPrivStats', n, scale)
}

clip_gradients_cpp <- function(grads, max_grad_norm) {
    .Call('_DPrivStats_clip_gradients_cpp', PACKAGE = 'DPrivStats', grads, max_grad_norm)
}

